### ISSUE TITLE
What about a Mac styled icon for OSX? 

### ISSUE THREAD

**Issue by PizzadatCode** [vergecurrency/verge-graphics#6]
<img width="604" alt="screen shot 2018-01-02 at 4 23 16 pm" src="https://user-images.githubusercontent.com/24704287/34505302-57036eca-efd9-11e7-8faa-927e01c2fc69.png">

**Comment by PizzadatCode** [comment]
I have it in PNG format, and can create the ICNS if desired.

**Comment by Ktesios** [comment]
nice of you to volunteer the time, but the graphic shouldn't be considered yet. The circle is crisp, but the 'W' gets choppy. Use the vector files to avoid issues.

**Comment by justinvforvendetta** [comment]
i like it. also we should consider making a few .icns files for more osx compat. ill copy the one from the wallet in here as well.

**Comment by justinvforvendetta** [comment]
@dbtftw did you ever make an icns from this?

**Comment by PizzadatCode** [comment]
@justinvforvendetta Yep they were submitted in a pull request a while ago. The Current OSX build uses this icon in ICNS format

**Comment by justinvforvendetta** [comment]
oh duh, i knew that. thanks man!
